package search.crawl.milano.common;

import java.util.HashMap;
import java.util.Map;

public class MilanoEnums {
	
	private static Map<Integer, DBReturnValues> codeToErrorsMap;
	
	private static void initMapping() {
		codeToErrorsMap = new HashMap<Integer, DBReturnValues>();
		
		for(DBReturnValues value : DBReturnValues.values()) {
			codeToErrorsMap.put(value.error_code, value);
		}
	}
	
	public enum DBReturnValues {
		ER_HASHCHK(1000, "hashchk "),
		ER_NISAMCHK(1001, "isamchk "),
		ER_NO(1002, "NO "),
		ER_YES(1003, "YES "),
		ER_CANT_CREATE_FILE(1004, "Can't create file '%s' (errno: %d) "),
		ER_CANT_CREATE_TABLE(1005, "Can't create table '%s' (errno: %d) "),
		ER_CANT_CREATE_DB(1006, "Can't create database '%s' (errno: %d) "),
		ER_DB_CREATE_EXISTS(1007, "Can't create database '%s'; database exists "),
		ER_DB_DROP_EXISTS(1008, "Can't drop database '%s'; database doesn't exist "),
		ER_DB_DROP_DELETE(1009, "Error dropping database (can't delete '%s', errno: %d)"),
		ER_DB_DROP_RMDIR(1010, "Error dropping database (can't rmdir '%s', errno: %d)"),
		ER_CANT_DELETE_FILE(1011, "Error on delete of '%s' (errno: %d) "),
		ER_CANT_FIND_SYSTEM_REC(1012, "Can't read record in system table "),
		ER_CANT_GET_STAT(1013, "Can't get status of '%s' (errno: %d) "),
		ER_CANT_GET_WD(1014, "Can't get working directory (errno: %d) "),
		ER_CANT_LOCK(1015, "Can't lock file (errno: %d) "),
		ER_CANT_OPEN_FILE(1016, "Can't open file: '%s' (errno: %d) "),
		ER_FILE_NOT_FOUND(1017, "Can't find file: '%s' (errno: %d)"),
		ER_CANT_READ_DIR(1018, "Can't read dir of '%s' (errno: %d) "),
		ER_CANT_SET_WD(1019, "Can't change dir to '%s' (errno: %d) "),
		ER_CHECKREAD(1020, "Record has changed since last read in table '%s' "),
		ER_DISK_FULL(1021, "Disk full (%s). Waiting for someone to free some space..."),
		ER_DUP_KEY(1022, "Can't write, duplicate key in table '%s' "),
		ER_ERROR_ON_CLOSE(1023, "Error on close of '%s' (errno: %d) "),
		ER_ERROR_ON_READ(1024, "Error reading file '%s' (errno: %d) "),
		ER_ERROR_ON_RENAME(1025, "Error on rename of '%s' to '%s' (errno: %d) "),
		ER_ERROR_ON_WRITE(1026, "Error writing file '%s' (errno: %d) "),
		ER_FILE_USED(1027, "'%s' is locked against change "),
		ER_FILSORT_ABORT(1028, "Sort aborted "),
		ER_FORM_NOT_FOUND(1029, "View '%s' doesn't exist for '%s' "),
		ER_GET_ERRNO(1030, "Got error %d from storage engine "),
		ER_ILLEGAL_HA(1031, "Table storage engine for '%s' doesn't have this option"),
		ER_KEY_NOT_FOUND(1032, "Can't find record in '%s' "),
		ER_NOT_FORM_FILE(1033, "Incorrect information in file: '%s' "),
		ER_NOT_KEYFILE(1034, "Incorrect key file for table: '%s'; try to repair it"),
		ER_OLD_KEYFILE(1035, "Old key file for table '%s'; repair it! "),
		ER_OPEN_AS_READONLY(1036, "Table '%s' is read only "),
		ER_OUTOFMEMORY(1037, "Out of memory. Restart daemon and try again (needed %d bytes) "),
		ER_OUT_OF_SORTMEMORY(1038, "Out of sort memory. Increase daemon sort buffer size"),
		ER_UNEXPECTED_EOF(1039, "Unexpected eof found when reading file '%s' (errno: %d)"),
		ER_CON_COUNT_ERROR(1040, "Too many connections "),
		ER_OUT_OF_RESOURCES(1041, "Out of memory; Check if mysqld or some other process uses all available memory. If not you may have to use 'ulimit' to allow mysqld to use more memory or you can add more swap space"),
		ER_BAD_HOST_ERROR(1042, "Can't get hostname for your address "),
		ER_HANDSHAKE_ERROR(1043, "Bad handshake "),
		ER_DBACCESS_DENIED_ERROR(1044, "Access denied for user: '%s'@'%s' to database '%s' "),
		ER_ACCESS_DENIED_ERROR(1045, "Access denied for user: '%s'@'%s' (Using password: %s)"),
		ER_NO_DB_ERROR(1046, "No Database Selected "),
		ER_UNKNOWN_COM_ERROR(1047, "Unknown command "),
		ER_BAD_NULL_ERROR(1048, "Column '%s' cannot be null "),
		ER_BAD_DB_ERROR(1049, "Unknown database '%s' "),
		ER_TABLE_EXISTS_ERROR(1050, "Table '%s' already exists "),
		ER_BAD_TABLE_ERROR(1051, "Unknown table '%s' "),
		ER_NON_UNIQ_ERROR(1052, "Column: '%s' in %s is ambiguous "),
		ER_SERVER_SHUTDOWN(1053, "Server shutdown in progress "),
		ER_BAD_FIELD_ERROR(1054, "Unknown column '%s' in '%s' "),
		ER_WRONG_FIELD_WITH_GROUP(1055, "'%s' isn't in GROUP BY "),
		ER_WRONG_GROUP_FIELD(1056, "Can't group on '%s' "),
		ER_WRONG_SUM_SELECT(1057, "Statement has sum functions and columns in same statement"),
		ER_WRONG_VALUE_COUNT(1058, "Column count doesn't match value count "),
		ER_TOO_LONG_IDENT(1059, "Identifier name '%s' is too long "),
		ER_DUP_FIELDNAME(1060, "Duplicate column name '%s' "),
		ER_DUP_KEYNAME(1061, "Duplicate key name '%s' "),
		ER_DUP_ENTRY(1062, "Duplicate entry '%s' for key %d "),
		ER_WRONG_FIELD_SPEC(1063, "Incorrect column specifier for column '%s' "),
		ER_PARSE_ERROR(1064, "%s near '%s' at line %d "),
		ER_EMPTY_QUERY(1065, "Query was empty "),
		ER_NONUNIQ_TABLE(1066, "Not unique table/alias: '%s' "),
		ER_INVALID_DEFAULT(1067, "Invalid default value for '%s' "),
		ER_MULTIPLE_PRI_KEY(1068, "Multiple primary key defined "),
		ER_TOO_MANY_KEYS(1069, "Too many keys specified. Max %d keys allowed "),
		ER_TOO_MANY_KEY_PARTS(1070, "Too many key parts specified. Max %d parts allowed "),
		ER_TOO_LONG_KEY(1071, "Specified key was too long. Max key length is %d "),
		ER_KEY_COLUMN_DOES_NOT_EXITS(1072, "Key column '%s' doesn't exist in table "),
		ER_BLOB_USED_AS_KEY(1073, "BLOB column '%s' can't be used in key specification with the used table type "),
		ER_TOO_BIG_FIELDLENGTH(1074, "Too big column length for column '%s' (max = %d). Use BLOB instead "),
		ER_WRONG_AUTO_KEY(1075, "Incorrect table definition; There can only be one auto column and it must be defined as a key "),
		ER_READY(1076, "%s: ready for connections. Version: '%s' socket: '%s' port: %d "),
		ER_NORMAL_SHUTDOWN(1077, "%s: Normal shutdown "),
		ER_GOT_SIGNAL(1078, "%s: Got signal %d. Aborting! "),
		ER_SHUTDOWN_COMPLETE(1079, "%s: Shutdown Complete "),
		ER_FORCING_CLOSE(1080, "%s: Forcing close of thread %ld user: '%s' "),
		ER_IPSOCK_ERROR(1081, "Can't create IP socket "),
		ER_NO_SUCH_INDEX(1082, "Table '%s' has no index like the one used in CREATE INDEX. Recreate the table "),
		ER_WRONG_FIELD_TERMINATORS(1083, "Field separator argument is not what is expected. Check the manual "),
		ER_BLOBS_AND_NO_TERMINATED(1084, "You can't use fixed rowlength with BLOBs. Please use 'fields terminated by' "),
		ER_TEXTFILE_NOT_READABLE(1085, "The file '%s' must be in the database directory or be readable by all "),
		ER_FILE_EXISTS_ERROR(1086, "File '%s' already exists "),
		ER_LOAD_INFO(1087, "Records: %ld Deleted: %ld Skipped: %ld Warnings: %ld"),
		ER_ALTER_INFO(1088, "Records: %ld Duplicates: %ld "),
		ER_WRONG_SUB_KEY(1089, "Incorrect sub part key. The used key part isn't a string, the used length is longer than the key part or the storage engine doesn't support unique sub keys "),
		ER_CANT_REMOVE_ALL_FIELDS(1090, "You can't delete all columns with ALTER TABLE. Use DROP TABLE instead "),
		ER_CANT_DROP_FIELD_OR_KEY(1091, "Can't DROP '%s'. Check that column/key exists "),
		ER_INSERT_INFO(1092, "Records: %ld Duplicates: %ld Warnings: %ld "),
		ER_UPDATE_TABLE_USED(1093, "You can't specify target table '%s' for update in FROM clause "),
		ER_NO_SUCH_THREAD(1094, "Unknown thread id: %lu "),
		ER_KILL_DENIED_ERROR(1095, "You are not owner of thread %lu "),
		ER_NO_TABLES_USED(1096, "No tables used "),
		ER_TOO_BIG_SET(1097, "Too many strings for column %s and SET "),
		ER_NO_UNIQUE_LOGFILE(1098, "Can't generate a unique log-filename %s.(1-999) "),
		ER_TABLE_NOT_LOCKED_FOR_WRITE(1099, "Table '%s' was locked with a READ lock and can't be updated "),
		ER_TABLE_NOT_LOCKED(1100, "Table '%s' was not locked with LOCK TABLES "),
		ER_BLOB_CANT_HAVE_DEFAULT(1101, "BLOB/TEXT column '%s' can't have a default value "),
		ER_WRONG_DB_NAME(1102, "Incorrect database name '%s' "),
		ER_WRONG_TABLE_NAME(1103, "Incorrect table name '%s' "),
		ER_TOO_BIG_SELECT(1104, "The SELECT would examine more rows than MAX_JOIN_SIZE. Check your WHERE and use SET SQL_BIG_SELECTS=1 or SET SQL_MAX_JOIN_SIZE=# if the SELECT is ok "),
		ER_UNKNOWN_ERROR(1105, "Unknown error "),
		ER_UNKNOWN_PROCEDURE(1106, "Unknown procedure '%s' "),
		ER_WRONG_PARAMCOUNT_TO_PROCEDURE(1107, "Incorrect parameter count to procedure '%s' "),
		ER_WRONG_PARAMETERS_TO_PROCEDURE(1108, "Incorrect parameters to procedure '%s' "),
		ER_UNKNOWN_TABLE(1109, "Unknown table '%s' in %s "),
		ER_FIELD_SPECIFIED_TWICE(1110, "Column '%s' specified twice "),
		ER_INVALID_GROUP_FUNC_USE(1111, "Invalid use of group function "),
		ER_UNSUPPORTED_EXTENSION(1112, "Table '%s' uses an extension that doesn't exist in this MySQL version "),
		ER_TABLE_MUST_HAVE_COLUMNS(1113, "A table must have at least 1 column "),
		ER_RECORD_FILE_FULL(1114, "The table '%s' is full "),
		ER_UNKNOWN_CHARACTER_SET(1115, "Unknown character set: '%s' "),
		ER_TOO_MANY_TABLES(1116, "Too many tables. MySQL can only use %d tables in a join"),
		ER_TOO_MANY_FIELDS(1117, "Too many columns "),
		ER_TOO_BIG_ROWSIZE(1118, "Too big row size. The maximum row size for the used table type, not counting BLOBs, is %ld. You have to change some fields to TEXT or BLOBs "),
		ER_STACK_OVERRUN(1119, "Thread stack overrun: Used: %ld of a %ld stack. Use 'mysqld -O thread_stack=#' to specify a bigger stack if needed"),
		ER_WRONG_OUTER_JOIN(1120, "Cross dependency found in OUTER JOIN. Examine your ON conditions "),
		ER_NULL_COLUMN_IN_INDEX(1121, "Column '%s' is used with UNIQUE or INDEX but is not defined as NOT NULL "),
		ER_CANT_FIND_UDF(1122, "Can't load function '%s' "),
		ER_CANT_INITIALIZE_UDF(1123, "Can't initialize function '%s'; %s "),
		ER_UDF_NO_PATHS(1124, "No paths allowed for shared library "),
		ER_UDF_EXISTS(1125, "Function '%s' already exist "),
		ER_CANT_OPEN_LIBRARY(1126, "Can't open shared library '%s' (errno: %d %s) "),
		ER_CANT_FIND_DL_ENTRY(1127, "Can't find function '%s' in library' "),
		ER_FUNCTION_NOT_DEFINED(1128, "Function '%s' is not defined "),
		ER_HOST_IS_BLOCKED(1129, "Host '%s' is blocked because of many connection errors. Unblock with 'mysqladmin flush-hosts' "),
		ER_HOST_NOT_PRIVILEGED(1130, "Host '%s' is not allowed to connect to this MySQL server"),
		ER_PASSWORD_ANONYMOUS_USER(1131, "You are using MySQL as an anonymous users and anonymous users are not allowed to change passwords "),
		ER_PASSWORD_NOT_ALLOWED(1132, "You must have privileges to update tables in the mysql database to be able to change passwords for others "),
		ER_PASSWORD_NO_MATCH(1133, "Can't find any matching row in the user table "),
		ER_UPDATE_INFO(1134, "Rows matched: %ld Changed: %ld Warnings: %ld "),
		ER_CANT_CREATE_THREAD(1135, "Can't create a new thread (errno %d). If you are not out of available memory, you can consult the manual for a possible OS-dependent bug "),
		ER_WRONG_VALUE_COUNT_ON_ROW(1136, "Column count doesn't match value count at row %ld "),
		ER_CANT_REOPEN_TABLE(1137, "Can't reopen table: '%s' "),
		ER_INVALID_USE_OF_NULL(1138, "Invalid use of NULL value "),
		ER_REGEXP_ERROR(1139, "Got error '%s' from regexp "),
		ER_MIX_OF_GROUP_FUNC_AND_FIELDS(1140, "Mixing of GROUP columns (MIN(),MAX(),COUNT()...) with no GROUP columns is illegal if there is no GROUP BY clause "),
		ER_NONEXISTING_GRANT(1141, "There is no such grant defined for user '%s' on host '%s'"),
		ER_TABLEACCESS_DENIED_ERROR(1142, "%s command denied to user: '%s'@'%s' for table '%s' "),
		ER_COLUMNACCESS_DENIED_ERROR(1143, "%s command denied to user: '%s'@'%s' for column '%s' in table '%s' "),
		ER_ILLEGAL_GRANT_FOR_TABLE(1144, "Illegal GRANT/REVOKE command. Please consult the manual which privileges can be used "),
		ER_GRANT_WRONG_HOST_OR_USER(1145, "The host or user argument to GRANT is too long "),
		ER_NO_SUCH_TABLE(1146, "Table '%s.%s' doesn't exist "),
		ER_NONEXISTING_TABLE_GRANT(1147, "There is no such grant defined for user '%s' on host '%s' on table '%s' "),
		ER_NOT_ALLOWED_COMMAND(1148, "The used command is not allowed with this MySQL version"),
		ER_SYNTAX_ERROR(1149, "You have an error in your SQL syntax. Check the manual that corresponds to your MySQL server version for the right syntax to use "),
		ER_DELAYED_CANT_CHANGE_LOCK(1150, "Delayed insert thread couldn't get requested lock for table %s "),
		ER_TOO_MANY_DELAYED_THREADS(1151, "Too many delayed threads in use "),
		ER_ABORTING_CONNECTION(1152, "Aborted connection %ld to db: '%s' user: '%s' (%s) "),
		ER_NET_PACKET_TOO_LARGE(1153, "Got a packet bigger than 'max_allowed_packet' "),
		ER_NET_READ_ERROR_FROM_PIPE(1154, "Got a read error from the connection pipe "),
		ER_NET_FCNTL_ERROR(1155, "Got an error from fcntl() "),
		ER_NET_PACKETS_OUT_OF_ORDER(1156, "Got packets out of order "),
		ER_NET_UNCOMPRESS_ERROR(1157, "Couldn't uncompress communication packet "),
		ER_NET_READ_ERROR(1158, "Got an error reading communication packets "),
		ER_NET_READ_INTERRUPTED(1159, "Got timeout reading communication packets "),
		ER_NET_ERROR_ON_WRITE(1160, "Got an error writing communication packets "),
		ER_NET_WRITE_INTERRUPTED(1161, "Got timeout writing communication packets "),
		ER_TOO_LONG_STRING(1162, "Result string is longer than max_allowed_packet "),
		ER_TABLE_CANT_HANDLE_BLOB(1163, "The used table type doesn't support BLOB/TEXT columns"),
		ER_TABLE_CANT_HANDLE_AUTO_INCREMENT(1164, "The used table type doesn't support AUTO_INCREMENT columns"),
		ER_DELAYED_INSERT_TABLE_LOCKED(1165, "INSERT DELAYED can't be used with table '%s' because it is locked with LOCK TABLES "),
		ER_WRONG_COLUMN_NAME(1166, "Incorrect column name '%s' "),
		ER_WRONG_KEY_COLUMN(1167, "The used storage engine can't index column '%s' "),
		ER_WRONG_MRG_TABLE(1168, "All tables in the MERGE table are not identically defined"),
		ER_DUP_UNIQUE(1169, "Can't write, because of unique constraint, to table '%s'"),
		ER_BLOB_KEY_WITHOUT_LENGTH(1170, "BLOB/TEXT column '%s' used in key specification without a key length "),
		ER_PRIMARY_CANT_HAVE_NULL(1171, "All parts of a PRIMARY KEY must be NOT NULL; If you need NULL in a key, use UNIQUE instead "),
		ER_TOO_MANY_ROWS(1172, "Result consisted of more than one row "),
		ER_REQUIRES_PRIMARY_KEY(1173, "This table type requires a primary key "),
		ER_NO_RAID_COMPILED(1174, "This version of MySQL is not compiled with RAID support"),
		ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE(1175, "You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column "),
		ER_KEY_DOES_NOT_EXITS(1176, "Key '%s' doesn't exist in table '%s' "),
		ER_CHECK_NO_SUCH_TABLE(1177, "Can't open table "),
		ER_CHECK_NOT_IMPLEMENTED(1178, "The storage engine for the table doesn't support %s "),
		ER_CANT_DO_THIS_DURING_AN_TRANSACTION(1179, "You are not allowed to execute this command in a transaction "),
		ER_ERROR_DURING_COMMIT(1180, "Got error %d during COMMIT "),
		ER_ERROR_DURING_ROLLBACK(1181, "Got error %d during ROLLBACK "),
		ER_ERROR_DURING_FLUSH_LOGS(1182, "Got error %d during FLUSH_LOGS "),
		ER_ERROR_DURING_CHECKPOINT(1183, "Got error %d during CHECKPOINT "),
		ER_NEW_ABORTING_CONNECTION(1184, "Aborted connection %ld to db: '%s' user: '%s' host: `%s' (%s) "),
		ER_DUMP_NOT_IMPLEMENTED(1185, "The storage engine for the table does not support binary table dump "),
		ER_FLUSH_MASTER_BINLOG_CLOSED(1186, "Binlog closed, cannot RESET MASTER "),
		ER_INDEX_REBUILD(1187, "Failed rebuilding the index of dumped table '%s' "),
		ER_MASTER(1188, "Error from master: '%s' "),
		ER_MASTER_NET_READ(1189, "Net error reading from master "),
		ER_MASTER_NET_WRITE(1190, "Net error writing to master "),
		ER_FT_MATCHING_KEY_NOT_FOUND(1191, "Can't find FULLTEXT index matching the column list "),
		ER_LOCK_OR_ACTIVE_TRANSACTION(1192, "Can't execute the given command because you have active locked tables or an active transaction "),
		ER_UNKNOWN_SYSTEM_VARIABLE(1193, "Unknown system variable '%s' "),
		ER_CRASHED_ON_USAGE(1194, "Table '%s' is marked as crashed and should be repaired"),
		ER_CRASHED_ON_REPAIR(1195, "Table '%s' is marked as crashed and last (automatic?) repair failed "),
		ER_WARNING_NOT_COMPLETE_ROLLBACK(1196, "Some non-transactional changed tables couldn't be rolled back "),
		ER_TRANS_CACHE_FULL(1197, "Multi-statement transaction required more than 'max_binlog_cache_size' bytes of storage. Increase this mysqld variable and try again "),
		ER_SLAVE_MUST_STOP(1198, "This operation cannot be performed with a running slave, run STOP SLAVE first "),
		ER_SLAVE_NOT_RUNNING(1199, "This operation requires a running slave, configure slave and do START SLAVE "),
		ER_BAD_SLAVE(1200, "The server is not configured as slave, fix in config file or with CHANGE MASTER TO "),
		ER_MASTER_INFO(1201, "Could not initialize master info structure, more error messages can be found in the MySQL error log "),
		ER_SLAVE_THREAD(1202, "Could not create slave thread, check system resources"),
		ER_TOO_MANY_USER_CONNECTIONS(1203, "User %s has already more than 'max_user_connections' active connections "),
		ER_SET_CONSTANTS_ONLY(1204, "You may only use constant expressions with SET "),
		ER_LOCK_WAIT_TIMEOUT(1205, "Lock wait timeout exceeded; Try restarting transaction"),
		ER_LOCK_TABLE_FULL(1206, "The total number of locks exceeds the lock table size"),
		ER_READ_ONLY_TRANSACTION(1207, "Update locks cannot be acquired during a READ UNCOMMITTED transaction "),
		ER_DROP_DB_WITH_READ_LOCK(1208, "DROP DATABASE not allowed while thread is holding global read lock "),
		ER_CREATE_DB_WITH_READ_LOCK(1209, "CREATE DATABASE not allowed while thread is holding global read lock "),
		ER_WRONG_ARGUMENTS(1210, "Wrong arguments to %s "),
		ER_NO_PERMISSION_TO_CREATE_USER(1211, "'%s'@'%s' is not allowed to create new users "),
		ER_UNION_TABLES_IN_DIFFERENT_DIR(1212, "Incorrect table definition; all MERGE tables must be in the same database "),
		ER_LOCK_DEADLOCK(1213, "Deadlock found when trying to get lock; Try restarting transaction "),
		ER_TABLE_CANT_HANDLE_FULLTEXT(1214, "The used table type doesn't support FULLTEXT indexes"),
		ER_CANNOT_ADD_FOREIGN(1215, "Cannot add foreign key constraint "),
		ER_NO_REFERENCED_ROW(1216, "Cannot add or update a child row: a foreign key constraint fails "),
		ER_ROW_IS_REFERENCED(1217, "Cannot delete or update a parent row: a foreign key constraint fails "),
		ER_CONNECT_TO_MASTER(1218, "Error connecting to master: %s "),
		ER_QUERY_ON_MASTER(1219, "Error running query on master: %s "),
		ER_ERROR_WHEN_EXECUTING_COMMAND(1220, "Error when executing command %s: %s "),
		ER_WRONG_USAGE(1221, "Wrong usage of %s and %s "),
		ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT(1222, "The used SELECT statements have a different number of columns "),
		ER_CANT_UPDATE_WITH_READLOCK(1223, "Can't execute the query because you have a conflicting read lock "),
		ER_MIXING_NOT_ALLOWED(1224, "Mixing of transactional and non-transactional tables is disabled "),
		ER_DUP_ARGUMENT(1225, "Option '%s' used twice in statement "),
		ER_USER_LIMIT_REACHED(1226, "User '%s' has exceeded the '%s' resource (current value: %ld) "),
		ER_SPECIFIC_ACCESS_DENIED_ERROR(1227, "Access denied. You need the %s privilege for this operation "),
		ER_LOCAL_VARIABLE(1228, "Variable '%s' is a LOCAL variable and can't be used with SET GLOBAL "),
		ER_GLOBAL_VARIABLE(1229, "Variable '%s' is a GLOBAL variable and should be set with SET GLOBAL "),
		ER_NO_DEFAULT(1230, "Variable '%s' doesn't have a default value "),
		ER_WRONG_VALUE_FOR_VAR(1231, "Variable '%s' can't be set to the value of '%s' "),
		ER_WRONG_TYPE_FOR_VAR(1232, "Wrong argument type to variable '%s' "),
		ER_VAR_CANT_BE_READ(1233, "Variable '%s' can only be set, not read "),
		ER_CANT_USE_OPTION_HERE(1234, "Wrong usage/placement of '%s' "),
		ER_NOT_SUPPORTED_YET(1235, "This version of MySQL doesn't yet support '%s' "),
		ER_MASTER_FATAL_ERROR_READING_BINLOG(1236, "Got fatal error %d: '%s' from master when reading data from binary log "),
		ER_SLAVE_IGNORED_TABLE(1237, "Slave SQL thread ignored the query because of replicate-*-table rules "),
		ER_INCORRECT_GLOBAL_LOCAL_VAR(1238, "Variable '%s' is a %s variable"),
		ER_WRONG_FK_DEF(1239, "Incorrect foreign key definition for '%s': %s"),
		ER_KEY_REF_DO_NOT_MATCH_TABLE_REF(1240, "Key reference and table reference don't match"),
		ER_OPERAND_COLUMNS(1241, "Operand should contain %d columns"),
		ER_SUBQUERY_NO_1_ROW(1242, "Subquery returns more than 1 row"),
		ER_UNKNOWN_STMT_HANDLER(1243, "Unknown prepared statement"),
		ER_CORRUPT_HELP_DB(1244, "Help database is corrupt or does not exist"),
		ER_CYCLIC_REFERENCE(1245, "Cyclic reference on subqueries"),
		ER_AUTO_CONVERT(1246, "Converting column '%s' from %s to %s"),
		ER_ILLEGAL_REFERENCE(1247, "Reference '%s' not"),
		ER_DERIVED_MUST_HAVE_ALIAS(1248, "Every derived table must have its own alias"),
		ER_SELECT_REDUCED(1249, "Select %u was reduced during optimization"),
		ER_TABLENAME_NOT_ALLOWED_HERE(1250, "Table '%s' from one of the SELECTs cannot be used in %s"),
		ER_NOT_SUPPORTED_AUTH_MODE(1251, "Client does not support authentication protocol requested by server; consider upgrading MySQL client"),
		ER_SPATIAL_CANT_HAVE_NULL(1252, "All parts of a SPATIAL index must be NOT NULL"),
		ER_COLLATION_CHARSET_MISMATCH(1253, "COLLATION '%s' is not valid for CHARACTER SET '%s'"),
		ER_SLAVE_WAS_RUNNING(1254, "Slave is already running"),
		ER_SLAVE_WAS_NOT_RUNNING(1255, "Slave already has been stopped"),
		ER_TOO_BIG_FOR_UNCOMPRESS(1256, "Uncompressed data size too large; the maximum size is %d probably, length of uncompressed data was corrupted"),
		ER_ZLIB_Z_MEM_ERROR(1257, "ZLIB: Not enough memory"),
		ER_ZLIB_Z_BUF_ERROR(1258, "ZLIB: Not enough room in the output"),
		ER_ZLIB_Z_DATA_ERROR(1259, "ZLIB: Input data corrupted"),
		ER_CUT_VALUE_GROUP_CONCAT(1260, "Row %u was cut by GROUP_CONCAT"),
		ER_WARN_TOO_FEW_RECORDS(1261, "Row %ld doesn't contain data for all columns"),
		ER_WARN_TOO_MANY_RECORDS(1262, "Row %ld was truncated; it contained more data than there were input columns"),
		ER_WARN_NULL_TO_NOTNULL(1263, "Column set to default value; NULL supplied to NOT NULL column '%s' at row %ld"),
		ER_WARN_DATA_OUT_OF_RANGE(1264, "Out of range value for column '%s' at row %ld"),
		WARN_DATA_TRUNCATED(1265, "Data truncated for column '%s' at row %ld"),
		ER_WARN_USING_OTHER_HANDLER(1266, "Using storage engine %s for table '%s'"),
		ER_CANT_AGGREGATE_2COLLATIONS(1267, "Illegal mix of"),
		ER_DROP_USER(1268, "Cannot drop one or more of the requested users"),
		ER_REVOKE_GRANTS(1269, "Can't revoke all privileges for one or more of the requested users"),
		ER_CANT_AGGREGATE_3COLLATIONS(1270, "Illegal mix of"),
		ER_CANT_AGGREGATE_NCOLLATIONS(1271, "Illegal mix of collations for operation '%s'"),
		ER_VARIABLE_IS_NOT_STRUCT(1272, "Variable '%s' is not a variable"),
		ER_UNKNOWN_COLLATION(1273, "Unknown collation: '%s'"),
		ER_SLAVE_IGNORED_SSL_PARAMS(1274, "SSL parameters in CHANGE MASTER are ignored because this MySQL slave was compiled without SSL support; they can be used later if MySQL slave with SSL is started"),
		ER_SERVER_IS_IN_SECURE_AUTH_MODE(1275, "Server is running in --secure-auth mode, but '%s'@'%s' has a password in the old format; please change the password to the new format"),
		ER_WARN_FIELD_RESOLVED(1276, "Field or reference '%s%s%s%s%s' of SELECT #%d was resolved in SELECT #%d"),
		ER_BAD_SLAVE_UNTIL_COND(1277, "Incorrect parameter or combination of parameters for START SLAVE UNTIL"),
		ER_MISSING_SKIP_SLAVE(1278, "It is recommended to use --skip-slave-start when doing step-by-step replication with START SLAVE UNTIL; otherwise, you will get problems if you get an unexpected slave's mysqld restart"),
		ER_UNTIL_COND_IGNORED(1279, "SQL thread is not to be started so UNTIL options are ignored"),
		ER_WRONG_NAME_FOR_INDEX(1280, "Incorrect index name '%s'"),
		ER_WRONG_NAME_FOR_CATALOG(1281, "Incorrect catalog name '%s'"),
		ER_WARN_QC_RESIZE(1282, "Query cache failed to set size %lu; new query cache size is %lu"),
		ER_BAD_FT_COLUMN(1283, "Column '%s' cannot be part of FULLTEXT index"),
		ER_UNKNOWN_KEY_CACHE(1284, "Unknown key cache '%s'"),
		ER_WARN_HOSTNAME_WONT_WORK(1285, "MySQL is started in --skip-name-resolve mode; you must restart it without this switch for this grant to work"),
		ER_UNKNOWN_STORAGE_ENGINE(1286, "Unknown storage engine '%s'"),
		ER_WARN_DEPRECATED_SYNTAX(1287, "'%s' is deprecated and will be removed in a future release. Please use %s instead"),
		ER_NON_UPDATABLE_TABLE(1288, "The target table %s of the %s is not updatable"),
		ER_FEATURE_DISABLED(1289, "The '%s' feature is disabled; you need MySQL built with '%s' to have it working"),
		ER_OPTION_PREVENTS_STATEMENT(1290, "The MySQL server is running with the %s option so it cannot execute this statement"),
		ER_DUPLICATED_VALUE_IN_TYPE(1291, "Column '%s' has duplicated value '%s' in %s"),
		ER_TRUNCATED_WRONG_VALUE(1292, "Truncated incorrect %s value: '%s'"),
		ER_TOO_MUCH_AUTO_TIMESTAMP_COLS(1293, "Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause"),
		ER_INVALID_ON_UPDATE(1294, "Invalid ON UPDATE clause for '%s' column"),
		ER_UNSUPPORTED_PS(1295, "This command is not supported in the prepared statement protocol yet"),
		ER_GET_ERRMSG(1296, "Got error %d '%s' from %s"),
		ER_GET_TEMPORARY_ERRMSG(1297, "Got temporary error %d '%s' from %s"),
		ER_UNKNOWN_TIME_ZONE(1298, "Unknown or incorrect time zone: '%s'"),
		ER_WARN_INVALID_TIMESTAMP(1299, "Invalid TIMESTAMP value in column '%s' at row %ld"),
		ER_INVALID_CHARACTER_STRING(1300, "Invalid %s character string: '%s'"),
		ER_WARN_ALLOWED_PACKET_OVERFLOWED(1301, "Result of %s) was larger than max_allowed_packet %ld) - truncated"),
		ER_CONFLICTING_DECLARATIONS(1302, "Conflicting declarations: '%s%s' and '%s%s'"),
		ER_SP_NO_RECURSIVE_CREATE(1303, "Can't create a %s from within another stored routine"),
		ER_SP_ALREADY_EXISTS(1304, "%s %s already exists"),
		ER_SP_DOES_NOT_EXIST(1305, "%s %s does not exist"),
		ER_SP_DROP_FAILED(1306, "Failed to DROP %s %s"),
		ER_SP_STORE_FAILED(1307, "Failed to CREATE %s %s"),
		ER_SP_LILABEL_MISMATCH(1308, "%s with no matching label: %s"),
		ER_SP_LABEL_REDEFINE(1309, "Redefining label %s"),
		ER_SP_LABEL_MISMATCH(1310, "End-label %s without match"),
		ER_SP_UNINIT_VAR(1311, "Referring to uninitialized variable %s"),
		ER_SP_BADSELECT(1312, "PROCEDURE %s can't return a result set in the given context"),
		ER_SP_BADRETURN(1313, "RETURN is only allowed in a FUNCTION"),
		ER_SP_BADSTATEMENT(1314, "%s is not allowed in stored procedures"),
		ER_UPDATE_LOG_DEPRECATED_IGNORED(1315, "The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been ignored. This option will be removed in MySQL 5.6."),
		ER_UPDATE_LOG_DEPRECATED_TRANSLATED(1316, "The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been translated to SET SQL_LOG_BIN. This option will be removed in MySQL 5.6."),
		ER_QUERY_INTERRUPTED(1317, "Query execution was interrupted"),
		ER_SP_WRONG_NO_OF_ARGS(1318, "Incorrect number of arguments for %s %s; expected %u, got %u"),
		ER_SP_COND_MISMATCH(1319, "Undefined CONDITION: %s"),
		ER_SP_NORETURN(1320, "No RETURN found in FUNCTION %s"),
		ER_SP_NORETURNEND(1321, "FUNCTION %s ended without RETURN"),
		ER_SP_BAD_CURSOR_QUERY(1322, "Cursor statement must be a SELECT"),
		ER_SP_BAD_CURSOR_SELECT(1323, "Cursor SELECT must not have INTO"),
		ER_SP_CURSOR_MISMATCH(1324, "Undefined CURSOR: %s"),
		ER_SP_CURSOR_ALREADY_OPEN(1325, "Cursor is already open"),
		ER_SP_CURSOR_NOT_OPEN(1326, "Cursor is not open"),
		ER_SP_UNDECLARED_VAR(1327, "Undeclared variable: %s"),
		ER_SP_WRONG_NO_OF_FETCH_ARGS(1328, "Incorrect number of FETCH variables"),
		ER_SP_FETCH_NO_DATA(1329, "No data - zero rows fetched, selected, or processed"),
		ER_SP_DUP_PARAM(1330, "Duplicate parameter: %s"),
		ER_SP_DUP_VAR(1331, "Duplicate variable: %s"),
		ER_SP_DUP_COND(1332, "Duplicate condition: %s"),
		ER_SP_DUP_CURS(1333, "Duplicate cursor: %s"),
		ER_SP_CANT_ALTER(1334, "Failed to ALTER %s %s"),
		ER_SP_SUBSELECT_NYI(1335, "Subquery value not supported"),
		ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG(1336, "%s is not allowed in stored function or trigger"),
		ER_SP_VARCOND_AFTER_CURSHNDLR(1337, "Variable or condition declaration after cursor or handler declaration"),
		ER_SP_CURSOR_AFTER_HANDLER(1338, "Cursor declaration after handler declaration"),
		ER_SP_CASE_NOT_FOUND(1339, "Case not found for CASE statement"),
		ER_FPARSER_TOO_BIG_FILE(1340, "Configuration file '%s' is too big"),
		ER_FPARSER_BAD_HEADER(1341, "Malformed file type header in file '%s'"),
		ER_FPARSER_EOF_IN_COMMENT(1342, "Unexpected end of file while parsing comment '%s'"),
		ER_FPARSER_ERROR_IN_PARAMETER(1343, "Error while parsing parameter '%s' line: '%s'"),
		ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER(1344, "Unexpected end of file while skipping unknown parameter '%s'"),
		ER_VIEW_NO_EXPLAIN(1345, "EXPLAIN/SHOW can not be issued; lacking privileges for underlying table"),
		ER_FRM_UNKNOWN_TYPE(1346, "File '%s' has unknown type '%s' in its header"),
		ER_WRONG_OBJECT(1347, "'%s.%s' is not %s"),
		ER_NONUPDATEABLE_COLUMN(1348, "Column '%s' is not updatable"),
		ER_VIEW_SELECT_DERIVED(1349, "View's SELECT contains a subquery in the FROM clause"),
		ER_VIEW_SELECT_CLAUSE(1350, "View's SELECT contains a '%s' clause"),
		ER_VIEW_SELECT_VARIABLE(1351, "View's SELECT contains a variable or parameter"),
		ER_VIEW_SELECT_TMPTABLE(1352, "View's SELECT refers to a temporary table '%s'"),
		ER_VIEW_WRONG_LIST(1353, "View's SELECT and view's field list have different column counts"),
		ER_WARN_VIEW_MERGE(1354, "View merge algorithm can't be used here for"),
		ER_WARN_VIEW_WITHOUT_KEY(1355, "View being updated does not have complete key of underlying table in it"),
		ER_VIEW_INVALID(1356, "View '%s.%s' references invalid tables) or columns) or functions) or definer/invoker of view lack rights to use them"),
		ER_SP_NO_DROP_SP(1357, "Can't drop or alter a %s from within another stored routine"),
		ER_SP_GOTO_IN_HNDLR(1358, "GOTO is not allowed in a stored procedure handler"),
		ER_TRG_ALREADY_EXISTS(1359, "Trigger already exists"),
		ER_TRG_DOES_NOT_EXIST(1360, "Trigger does not exist"),
		ER_TRG_ON_VIEW_OR_TEMP_TABLE(1361, "Trigger's '%s' is view or temporary table"),
		ER_TRG_CANT_CHANGE_ROW(1362, "Updating of %s row is not allowed in %strigger"),
		ER_TRG_NO_SUCH_ROW_IN_TRG(1363, "There is no %s row in %s trigger"),
		ER_NO_DEFAULT_FOR_FIELD(1364, "Field '%s' doesn't have a default value"),
		ER_DIVISION_BY_ZERO(1365, "Division by 0"),
		ER_TRUNCATED_WRONG_VALUE_FOR_FIELD(1366, "Incorrect %s value: '%s' for column '%s' at row %ld"),
		ER_ILLEGAL_VALUE_FOR_TYPE(1367, "Illegal %s '%s' value found during parsing"),
		ER_VIEW_NONUPD_CHECK(1368, "CHECK OPTION on non-updatable view '%s.%s'"),
		ER_VIEW_CHECK_FAILED(1369, "CHECK OPTION failed '%s.%s'"),
		ER_PROCACCESS_DENIED_ERROR(1370, "%s command denied to user '%s'@'%s' for routine '%s'"),
		ER_RELAY_LOG_FAIL(1371, "Failed purging old relay logs: %s"),
		ER_PASSWD_LENGTH(1372, "Password hash should be a %d-digit hexadecimal number"),
		ER_UNKNOWN_TARGET_BINLOG(1373, "Target log not found in binlog index"),
		ER_IO_ERR_LOG_INDEX_READ(1374, "I/O error reading log index file"),
		ER_BINLOG_PURGE_PROHIBITED(1375, "Server configuration does not permit binlog purge"),
		ER_FSEEK_FAIL(1376, "Failed on fseek"),
		ER_BINLOG_PURGE_FATAL_ERR(1377, "Fatal error during log purge"),
		ER_LOG_IN_USE(1378, "A purgeable log is in use, will not purge"),
		ER_LOG_PURGE_UNKNOWN_ERR(1379, "Unknown error during log purge"),
		ER_RELAY_LOG_INIT(1380, "Failed initializing relay log position: %s"),
		ER_NO_BINARY_LOGGING(1381, "You are not using binary logging"),
		ER_RESERVED_SYNTAX(1382, "The '%s' syntax is reserved for purposes internal to the MySQL server"),
		ER_WSAS_FAILED(1383, "WSAStartup Failed"),
		ER_DIFF_GROUPS_PROC(1384, "Can't handle procedures with different groups yet"),
		ER_NO_GROUP_FOR_PROC(1385, "Select must have a group with this procedure"),
		ER_ORDER_WITH_PROC(1386, "Can't use ORDER clause with this procedure"),
		ER_LOGGING_PROHIBIT_CHANGING_OF(1387, "Binary logging and replication forbid changing the global server %s"),
		ER_NO_FILE_MAPPING(1388, "Can't map file: %s, errno: %d"),
		ER_WRONG_MAGIC(1389, "Wrong magic in %s"),
		ER_PS_MANY_PARAM(1390, "Prepared statement contains too many placeholders"),
		ER_KEY_PART_0(1391, "Key part '%s' length cannot be 0"),
		ER_VIEW_CHECKSUM(1392, "View text checksum failed"),
		ER_VIEW_MULTIUPDATE(1393, "Can not modify more than one base table through a join view '%s.%s'"),
		ER_VIEW_NO_INSERT_FIELD_LIST(1394, "Can not insert into join view '%s.%s' without fields list"),
		ER_VIEW_DELETE_MERGE_VIEW(1395, "Can not delete from join view '%s.%s'"),
		ER_CANNOT_USER(1396, "Operation %s failed for %s"),
		ER_XAER_NOTA(1397, "XAER_NOTA: Unknown XID"),
		ER_XAER_INVAL(1398, "XAER_INVAL: Invalid"),
		ER_XAER_RMFAIL(1399, "XAER_RMFAIL: The command cannot be executed when global transaction is in the %s state"),
		ER_XAER_OUTSIDE(1400, "XAER_OUTSIDE: Some work is done outside global transaction"),
		ER_XAER_RMERR(1401, "XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency"),
		ER_XA_RBROLLBACK(1402, "XA_RBROLLBACK: Transaction branch was rolled back"),
		ER_NONEXISTING_PROC_GRANT(1403, "There is no such grant defined for user '%s' on host '%s' on routine '%s'"),
		ER_PROC_AUTO_GRANT_FAIL(1404, "Failed to grant EXECUTE and ALTER ROUTINE privileges"),
		ER_PROC_AUTO_REVOKE_FAIL(1405, "Failed to revoke all privileges to dropped routine"),
		ER_DATA_TOO_LONG(1406, "Data too long for column '%s' at row %ld"),
		ER_SP_BAD_SQLSTATE(1407, "Bad '%s'"),
		ER_STARTUP(1408, "%s: ready for connections. Version: '%s' socket: '%s' port: %d %s"),
		ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR(1409, "Can't load value from file with fixed size rows to variable"),
		ER_CANT_CREATE_USER_WITH_GRANT(1410, "You are not allowed to create a user with GRANT"),
		ER_WRONG_VALUE_FOR_TYPE(1411, "Incorrect %s value: '%s' for function %s"),
		ER_TABLE_DEF_CHANGED(1412, "Table definition has changed, please retry transaction"),
		ER_SP_DUP_HANDLER(1413, "Duplicate handler declared in the same block"),
		ER_SP_NOT_VAR_ARG(1414, "OUT or INOUT argument %d for routine %s is not a variable or NEW pseudo-variable in BEFORE trigger"),
		ER_SP_NO_RETSET(1415, "Not allowed to return a result set from a %s"),
		ER_CANT_CREATE_GEOMETRY_OBJECT(1416, "Cannot get geometry object from data you send to the GEOMETRY field"),
		ER_FAILED_ROUTINE_BREAK_BINLOG(1417, "A routine failed and has neither NO SQL nor READS SQL DATA in its declaration and binary logging is enabled; if non-transactional tables were updated, the binary log will miss their changes"),
		ER_BINLOG_UNSAFE_ROUTINE(1418, "This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is"),
		ER_BINLOG_CREATE_ROUTINE_NEED_SUPER(1419, "You do not have the SUPER privilege and binary logging is"),
		ER_EXEC_STMT_WITH_OPEN_CURSOR(1420, "You can't execute a prepared statement which has an open cursor associated with it. Reset the statement to re-execute it."),
		ER_STMT_HAS_NO_OPEN_CURSOR(1421, "The"),
		ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG(1422, "Explicit or implicit commit is not allowed in stored function or trigger."),
		ER_NO_DEFAULT_FOR_VIEW_FIELD(1423, "Field of view '%s.%s' underlying table doesn't have a default value"),
		ER_SP_NO_RECURSION(1424, "Recursive stored functions and triggers are not allowed."),
		ER_TOO_BIG_SCALE(1425, "Too big scale %d specified for column '%s'. Maximum is %lu."),
		ER_TOO_BIG_PRECISION(1426, "Too big precision %d specified for column '%s'. Maximum is %lu."),
		ER_M_BIGGER_THAN_D(1427, "For floatM,D), doubleM,D) or decimalM,D), M must be >="),
		ER_WRONG_LOCK_OF_SYSTEM_TABLE(1428, "You can't combine write-locking of system tables with other tables or lock types"),
		ER_CONNECT_TO_FOREIGN_DATA_SOURCE(1429, "Unable to connect to foreign data source: %s"),
		ER_QUERY_ON_FOREIGN_DATA_SOURCE(1430, "There was a problem processing the query on the foreign data source. Data source%s"),
		ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST(1431, "The foreign data source you are trying to reference does not exist. Data source%s"),
		ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE(1432, "Can't create federated table. The data source connection string '%s' is not in the correct format"),
		ER_FOREIGN_DATA_STRING_INVALID(1433, "The data source connection string '%s' is not in the correct format"),
		ER_CANT_CREATE_FEDERATED_TABLE(1434, "Can't create federated table. Foreign data src%s"),
		ER_TRG_IN_WRONG_SCHEMA(1435, "Trigger in wrong schema"),
		ER_STACK_OVERRUN_NEED_MORE(1436, "Thread stack overrun: %ld bytes used of a %ld byte stack, and %ld bytes needed. Use 'mysqld --thread_stack=#' to specify a bigger stack."),
		ER_TOO_LONG_BODY(1437, "Routine body for '%s' is too long"),
		ER_WARN_CANT_DROP_DEFAULT_KEYCACHE(1438, "Cannot drop default keycache"),
		ER_TOO_BIG_DISPLAYWIDTH(1439, "Display width out of range for column '%s' max = %lu"),
		ER_XAER_DUPID(1440, "XAER_DUPID: The XID already exists"),
		ER_DATETIME_FUNCTION_OVERFLOW(1441, "Datetime function: %s field overflow"),
		ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG(1442, "Can't update table '%s' in stored function/trigger because it is already used by statement which invoked this stored function/trigger."),
		ER_VIEW_PREVENT_UPDATE(1443, "The definition of table '%s' prevents operation %s on table '%s'."),
		ER_PS_NO_RECURSION(1444, "The prepared statement contains a stored routine call that refers to that same statement. It's not allowed to execute a prepared statement in such a recursive manner"),
		ER_SP_CANT_SET_AUTOCOMMIT(1445, "Not allowed to set autocommit from a stored function or trigger"),
		ER_MALFORMED_DEFINER(1446, "Definer is not fully qualified"),
		ER_VIEW_FRM_NO_USER(1447, "View '%s'.'%s' has no definer"),
		ER_VIEW_OTHER_USER(1448, "You need the SUPER privilege for creation view with '%s'@'%s' definer"),
		ER_NO_SUCH_USER(1449, "The user specified as a"),
		ER_FORBID_SCHEMA_CHANGE(1450, "Changing schema from '%s' to '%s' is not allowed."),
		ER_ROW_IS_REFERENCED_2(1451, "Cannot delete or update a parent row: a foreign key constraint"),
		ER_NO_REFERENCED_ROW_2(1452, "Cannot add or update a child row: a foreign key constraint"),
		ER_SP_BAD_VAR_SHADOW(1453, "Variable '%s' must be quoted with `...`, or renamed"),
		ER_TRG_NO_DEFINER(1454, "No definer attribute for trigger '%s'.'%s'. The trigger will be activated under the authorization of the invoker, which may have insufficient privileges. Please recreate the trigger."),
		ER_OLD_FILE_FORMAT(1455, "'%s' has an old format, you should re-create the '%s' objects"),
		ER_SP_RECURSION_LIMIT(1456, "Recursive limit %d as set by the max_sp_recursion_depth variable) was exceeded for routine %s"),
		ER_SP_PROC_TABLE_CORRUPT(1457, "Failed to load routine %s. The table mysql.proc is missing, corrupt, or contains bad"),
		ER_SP_WRONG_NAME(1458, "Incorrect routine name '%s'"),
		ER_TABLE_NEEDS_UPGRADE(1459, "Table upgrade required. Please do 'REPAIR TABLE `%s`' or dump/reload to fix it!"),
		ER_SP_NO_AGGREGATE(1460, "AGGREGATE is not supported for stored functions"),
		ER_MAX_PREPARED_STMT_COUNT_REACHED(1461, "Can't create more than max_prepared_stmt_count"),
		ER_VIEW_RECURSIVE(1462, "`%s`.`%s` contains view recursion"),
		ER_NON_GROUPING_FIELD_USED(1463, "non-grouping field '%s' is used in %s clause"),
		ER_TABLE_CANT_HANDLE_SPKEYS(1464, "The used table type doesn't support SPATIAL indexes"),
		ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA(1465, "Triggers can not be created on system tables"),
		ER_REMOVED_SPACES(1466, "Leading spaces are removed from name '%s'"),
		ER_AUTOINC_READ_FAILED(1467, "Failed to read auto-increment value from storage engine"),
		ER_USERNAME(1468, "user name"),
		ER_HOSTNAME(1469, "host name"),
		ER_WRONG_STRING_LENGTH(1470, "String '%s' is too long for %s should be no longer than %d"),
		ER_NON_INSERTABLE_TABLE(1471, "The target table %s of the %s is not insertable-into"),
		ER_ADMIN_WRONG_MRG_TABLE(1472, "Table '%s' is differently defined or of non-MyISAM type or doesn't exist"),
		ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT(1473, "Too high level of nesting for select"),
		ER_NAME_BECOMES_EMPTY(1474, "Name '%s' has become ''"),
		ER_AMBIGUOUS_FIELD_TERM(1475, "First character of the FIELDS TERMINATED string is ambiguous; please use non-optional and non-empty FIELDS ENCLOSED BY"),
		ER_FOREIGN_SERVER_EXISTS(1476, "The foreign server, %s, you are trying to create already exists."),
		ER_FOREIGN_SERVER_DOESNT_EXIST(1477, "The foreign server name you are trying to reference does not exist. Data source%s"),
		ER_ILLEGAL_HA_CREATE_OPTION(1478, "Table storage engine '%s' does not support the create option '%s'"),
		ER_PARTITION_REQUIRES_VALUES_ERROR(1479, "Syntax%s PARTITIONING requires definition of VALUES %s for each partition"),
		ER_PARTITION_WRONG_VALUES_ERROR(1480, "Only %s PARTITIONING can use VALUES %s in partition definition"),
		ER_PARTITION_MAXVALUE_ERROR(1481, "MAXVALUE can only be used in last partition definition"),
		ER_PARTITION_SUBPARTITION_ERROR(1482, "Subpartitions can only be hash partitions and by key"),
		ER_PARTITION_SUBPART_MIX_ERROR(1483, "Must define subpartitions on all partitions if on one partition"),
		ER_PARTITION_WRONG_NO_PART_ERROR(1484, "Wrong number of partitions defined, mismatch with previous setting"),
		ER_PARTITION_WRONG_NO_SUBPART_ERROR(1485, "Wrong number of subpartitions defined, mismatch with previous setting"),
		ER_WRONG_EXPR_IN_PARTITION_FUNC_ERROR(1486, "Constant, random or timezone-dependent expressions"),
		ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR(1487, "Expression in RANGE/LIST VALUES must be constant"),
		ER_FIELD_NOT_FOUND_PART_ERROR(1488, "Field in list of fields for partition function not found in table"),
		ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR(1489, "List of fields is only allowed in KEY partitions"),
		ER_INCONSISTENT_PARTITION_INFO_ERROR(1490, "The partition info in the frm file is not consistent with what can be written into the frm file"),
		ER_PARTITION_FUNC_NOT_ALLOWED_ERROR(1491, "The %s function returns the wrong type"),
		ER_PARTITIONS_MUST_BE_DEFINED_ERROR(1492, "For %s partitions each partition must be defined"),
		ER_RANGE_NOT_INCREASING_ERROR(1493, "VALUES LESS THAN value must be strictly increasing for each partition"),
		ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR(1494, "VALUES value must be of same type as partition function"),
		ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR(1495, "Multiple definition of same constant in list partitioning"),
		ER_PARTITION_ENTRY_ERROR(1496, "Partitioning can not be used stand-alone in query"),
		ER_MIX_HANDLER_ERROR(1497, "The mix of handlers in the partitions is not allowed in this version of MySQL"),
		ER_PARTITION_NOT_DEFINED_ERROR(1498, "For the partitioned engine it is necessary to define all %s"),
		ER_TOO_MANY_PARTITIONS_ERROR(1499, "Too many"),
		ER_SUBPARTITION_ERROR(1500, "It is only possible to mix RANGE/LIST partitioning with HASH/KEY partitioning for subpartitioning."),		
		SUCCESS(0000, "Succes.");
			

		
		private final int error_code;
		private final String message;
		
		DBReturnValues(int error_code, String message) {
			this.error_code = error_code;
			this.message = message;
		}
		
		public int getErrorCode() { 
			return this.error_code;
		}
		
		public String getMessage() { 
			return this.message;
		}
		
		public static DBReturnValues getErrors(int errorCode) {
			if(codeToErrorsMap == null) {
				initMapping();
			}
			return codeToErrorsMap.get(errorCode);
		}
	}
}
